import type { Metadata } from 'next'
import { Inter, Raleway } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'

// const inter = Inter({ subsets: ['latin'] })
const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chat Interface (Task 1)',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        {/* Main Container */}
        <main className='container w-full max-w-7xl p-3 lg:px-4 space-y-2 min-h-screen'>
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  )
}
